// Generated by gir (https://github.com/gtk-rs/gir @ 3f715d99469c)
// from ../gir-files (@ 6525c06593ee)
// DO NOT EDIT

#include "manual.h"
#include <stdalign.h>
#include <stdio.h>

int main() {
    printf("%s;%zu;%zu\n", "GIArgInfo", sizeof(GIArgInfo), alignof(GIArgInfo));
    printf("%s;%zu;%zu\n", "GIArgument", sizeof(GIArgument), alignof(GIArgument));
    printf("%s;%zu;%zu\n", "GIArrayType", sizeof(GIArrayType), alignof(GIArrayType));
    printf("%s;%zu;%zu\n", "GIAttributeIter", sizeof(GIAttributeIter), alignof(GIAttributeIter));
    printf("%s;%zu;%zu\n", "GIBaseInfo", sizeof(GIBaseInfo), alignof(GIBaseInfo));
    printf("%s;%zu;%zu\n", "GICallableInfo", sizeof(GICallableInfo), alignof(GICallableInfo));
    printf("%s;%zu;%zu\n", "GICallbackInfo", sizeof(GICallbackInfo), alignof(GICallbackInfo));
    printf("%s;%zu;%zu\n", "GIConstantInfo", sizeof(GIConstantInfo), alignof(GIConstantInfo));
    printf("%s;%zu;%zu\n", "GIDirection", sizeof(GIDirection), alignof(GIDirection));
    printf("%s;%zu;%zu\n", "GIEnumInfo", sizeof(GIEnumInfo), alignof(GIEnumInfo));
    printf("%s;%zu;%zu\n", "GIFieldInfo", sizeof(GIFieldInfo), alignof(GIFieldInfo));
    printf("%s;%zu;%zu\n", "GIFieldInfoFlags", sizeof(GIFieldInfoFlags), alignof(GIFieldInfoFlags));
    printf("%s;%zu;%zu\n", "GIFunctionInfo", sizeof(GIFunctionInfo), alignof(GIFunctionInfo));
    printf("%s;%zu;%zu\n", "GIFunctionInfoFlags", sizeof(GIFunctionInfoFlags), alignof(GIFunctionInfoFlags));
    printf("%s;%zu;%zu\n", "GIInfoType", sizeof(GIInfoType), alignof(GIInfoType));
    printf("%s;%zu;%zu\n", "GIInterfaceInfo", sizeof(GIInterfaceInfo), alignof(GIInterfaceInfo));
    printf("%s;%zu;%zu\n", "GIObjectInfo", sizeof(GIObjectInfo), alignof(GIObjectInfo));
    printf("%s;%zu;%zu\n", "GIPropertyInfo", sizeof(GIPropertyInfo), alignof(GIPropertyInfo));
    printf("%s;%zu;%zu\n", "GIRegisteredTypeInfo", sizeof(GIRegisteredTypeInfo), alignof(GIRegisteredTypeInfo));
    printf("%s;%zu;%zu\n", "GIRepository", sizeof(GIRepository), alignof(GIRepository));
    printf("%s;%zu;%zu\n", "GIRepositoryClass", sizeof(GIRepositoryClass), alignof(GIRepositoryClass));
    printf("%s;%zu;%zu\n", "GIRepositoryError", sizeof(GIRepositoryError), alignof(GIRepositoryError));
    printf("%s;%zu;%zu\n", "GIRepositoryLoadFlags", sizeof(GIRepositoryLoadFlags), alignof(GIRepositoryLoadFlags));
    printf("%s;%zu;%zu\n", "GIScopeType", sizeof(GIScopeType), alignof(GIScopeType));
    printf("%s;%zu;%zu\n", "GISignalInfo", sizeof(GISignalInfo), alignof(GISignalInfo));
    printf("%s;%zu;%zu\n", "GIStructInfo", sizeof(GIStructInfo), alignof(GIStructInfo));
    printf("%s;%zu;%zu\n", "GITransfer", sizeof(GITransfer), alignof(GITransfer));
    printf("%s;%zu;%zu\n", "GITypeInfo", sizeof(GITypeInfo), alignof(GITypeInfo));
    printf("%s;%zu;%zu\n", "GITypeTag", sizeof(GITypeTag), alignof(GITypeTag));
    printf("%s;%zu;%zu\n", "GIUnionInfo", sizeof(GIUnionInfo), alignof(GIUnionInfo));
    printf("%s;%zu;%zu\n", "GIVFuncInfo", sizeof(GIVFuncInfo), alignof(GIVFuncInfo));
    printf("%s;%zu;%zu\n", "GIVFuncInfoFlags", sizeof(GIVFuncInfoFlags), alignof(GIVFuncInfoFlags));
    printf("%s;%zu;%zu\n", "GIValueInfo", sizeof(GIValueInfo), alignof(GIValueInfo));
    printf("%s;%zu;%zu\n", "GInvokeError", sizeof(GInvokeError), alignof(GInvokeError));
    return 0;
}
