[options]
library = "GIRepository"
version = "2.0"
min_cfg_version = "1.72.0"
target_path = "."
girs_directories = ["./gir-files/"]
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true

generate = [
    "GIRepository.BaseInfo",
    #     "GIRepository.ArgInfo",

    "GIRepository.Repository",
    "GIRepository.EnumInfo",
    "GIRepository.InterfaceInfo",
    "GIRepository.RepositoryLoadFlags",
    # "GIRepository.Typelib", # Missing memory management functions
]

manual = [
    "GIRepository.Typelib",

    "GLib.Error",
    "GLib.Quark",
    # "GLib.OptionGroup",
]