// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files
// DO NOT EDIT

#[allow(unused_imports)]
use crate::auto::*;

pub type ArgInfo = crate::BaseInfo;
pub type CallableInfo = crate::BaseInfo;
pub type CallbackInfo = crate::BaseInfo;
pub type ConstantInfo = crate::BaseInfo;
pub type EnumInfo = crate::BaseInfo;
pub type FieldInfo = crate::BaseInfo;
pub type FunctionInfo = crate::BaseInfo;
pub type InterfaceInfo = crate::BaseInfo;
pub type ObjectInfo = crate::BaseInfo;
pub type PropertyInfo = crate::BaseInfo;
pub type RegisteredTypeInfo = crate::BaseInfo;
pub type SignalInfo = crate::BaseInfo;
pub type StructInfo = crate::BaseInfo;
pub type TypeInfo = crate::BaseInfo;
pub type UnionInfo = crate::BaseInfo;
pub type VFuncInfo = crate::BaseInfo;
pub type ValueInfo = crate::BaseInfo;
